<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Dapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dusiburg.AI.Sinistri.Core\Dusiburg.AI.Sinistri.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dusiburg.AI.Sinistri.Tests" />
  </ItemGroup>

</Project>
